version: '3.7'
services:
    postgres:
        image: postgres:14
        restart: always
        env_file:
            - ./postgres/prod.env
        ports:
            - '5430:5432'
        volumes:
            - database:/var/lib/postgresql/data
    api:
        ports:
            - '2015:2015'
        build: ./api
        restart: always
        env_file:
            - ./api/prod.env
        environment:
            - DATABASE_HOST=postgres
            - NODE_ENV=production
        depends_on:
            - postgres
    web-app:
        ports:
            - '2008:2008'
        build: ./web-app
        restart: always
        env_file:
            - ./web-app/prod.env
        depends_on:
            - api
    nginx:
        depends_on:
            - web-app
            - postgres
            - api
        restart: always
        build: ./nginx
        ports:
            - '80:80'
            - '443:443'

volumes:
    database:
