name: api

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "This job's status is ${{ job.status }}."