name: API CI

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17'
      - name: Install dependencies
        run: cd api && npm ci
      - run: cd api && npm run build --if-present
      - run: cd api && npm run test