name: API CI

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "cd .github && cd workflows && api.yaml" up -d --build

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install dependencies
        run: cd api && npm ci

      - name: Run build if present
        run: cd api && npm run build --if-present

      - name: Run test
        run: cd api && npm run test