name: Test app

on: [push]

jobs:
  lint_app:
    name: Lint app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint

  test_app:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          docker version
      - run: docker-compose build
      - run: docker-compose up -d

      
      